from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ProtectedSpan:
    kind: str
    source_text: str
    canonical: str
    spoken: str
    display: str
    start_char: int
    end_char: int
    confidence: float
    rule_id: str
    forbidden: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, object]:
        return {
            "kind": self.kind,
            "source_text": self.source_text,
            "canonical": self.canonical,
            "spoken": self.spoken,
            "display": self.display,
            "start_char": self.start_char,
            "end_char": self.end_char,
            "confidence": self.confidence,
            "rule_id": self.rule_id,
            "forbidden": list(self.forbidden),
        }


@dataclass(frozen=True)
class DomainProfile:
    profile_id: str
    version: str
    prompt_summary: str
    glossary_seeds: list[dict[str, object]] = field(default_factory=list)
    forbidden_translations: dict[str, list[str]] = field(default_factory=dict)

    @property
    def artifact_id(self) -> str:
        return f"{self.profile_id}@{self.version}"


_PROFILE_ALIASES = {
    "calculus": "calculus",
    "mathematics": "calculus",
    "math": "calculus",
    "educational math": "calculus",
}

_WORD_BOUNDARY = r"(?<![A-Za-zÀ-ỹ]){token}(?![A-Za-zÀ-ỹ])"


def load_domain_profile(domain: str, explicit_profile: str = "") -> DomainProfile:
    requested = (explicit_profile or domain or "general").strip().lower()
    profile_id = _PROFILE_ALIASES.get(requested, requested)
    if profile_id != "calculus":
        return DomainProfile(
            profile_id="generic",
            version="1",
            prompt_summary="Generic educational content. Preserve names, symbols, units, formulas, and numbers exactly when translation would change meaning.",
        )
    return _load_calculus_profile()


def detect_protected_spans(text: str, profile: DomainProfile) -> list[ProtectedSpan]:
    if profile.profile_id != "calculus":
        return []
    spans = _detect_calculus_spans(text)
    return _dedupe_spans(spans)


def glossary_terms_from_spans(
    spans: list[ProtectedSpan],
    *,
    source_segments: list[str],
    locked: bool,
) -> list[dict[str, object]]:
    terms: list[dict[str, object]] = []
    seen: set[str] = set()
    for span in spans:
        key = span.canonical.lower()
        if key in seen:
            continue
        seen.add(key)
        terms.append(
            {
                "term_id": f"protected_{_safe_id(span.canonical)}",
                "original": span.canonical,
                "vietnamese": span.spoken,
                "category": span.kind,
                "confidence": span.confidence,
                "locked": locked,
                "source_segments": source_segments,
                "notes": f"Domain protected span generated by {span.rule_id}.",
                "protected": True,
                "spoken": span.spoken,
                "display": span.display,
                "forbidden": list(span.forbidden),
            }
        )
    return terms


def normalize_spoken_text(display_text: str, protected_spans: list[ProtectedSpan | dict[str, object]]) -> str:
    text = display_text
    replacements: list[tuple[str, str]] = []
    for span in protected_spans:
        if isinstance(span, ProtectedSpan):
            canonical = span.canonical
            spoken = span.spoken
            display = span.display
        else:
            canonical = str(span.get("canonical", ""))
            spoken = str(span.get("spoken", ""))
            display = str(span.get("display", ""))
        if spoken:
            for original in (display, canonical):
                if original and original != spoken:
                    replacements.append((original, spoken))
    replacements.extend(
        [
            ("dy/dx", "d y trên d x"),
            ("d/dx", "d trên d x"),
            ("d/dt", "d trên d t"),
            ("πr²", "pi r bình phương"),
            ("π r²", "pi r bình phương"),
            ("½", "một phần hai"),
            ("×", " nhân "),
        ]
    )
    for original, spoken in sorted(replacements, key=lambda item: len(item[0]), reverse=True):
        if not original:
            continue
        text = re.sub(re.escape(original), spoken, text, flags=re.IGNORECASE)
    text = re.sub(r"(?<![A-Za-zÀ-ỹ])dr(?![A-Za-zÀ-ỹ])", "d r", text, flags=re.IGNORECASE)
    text = re.sub(r"(?<![A-Za-zÀ-ỹ])dx(?![A-Za-zÀ-ỹ])", "d x", text, flags=re.IGNORECASE)
    text = re.sub(r"(?<![A-Za-zÀ-ỹ])dy(?![A-Za-zÀ-ỹ])", "d y", text, flags=re.IGNORECASE)
    text = re.sub(r"(?<![A-Za-zÀ-ỹ])dt(?![A-Za-zÀ-ỹ])", "d t", text, flags=re.IGNORECASE)
    text = re.sub(r"([A-Za-zÀ-ỹ])²", r"\1 bình phương", text)
    text = re.sub(r"([A-Za-zÀ-ỹ])³", r"\1 lập phương", text)
    return re.sub(r"\s+", " ", text).strip()


def protected_spans_prompt(spans: list[ProtectedSpan | dict[str, object]]) -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for span in spans:
        item = span.to_dict() if isinstance(span, ProtectedSpan) else dict(span)
        result.append(
            {
                "canonical": item.get("canonical", ""),
                "source_text": item.get("source_text", ""),
                "display": item.get("display", ""),
                "spoken": item.get("spoken", ""),
                "kind": item.get("kind", ""),
                "forbidden": item.get("forbidden", []),
            }
        )
    return result



def protected_translation_errors(
    source_text: str,
    translated_text: str,
    protected_spans: list[ProtectedSpan | dict[str, object]],
) -> list[str]:
    if not protected_spans:
        return []
    lower = translated_text.lower()
    spoken = normalize_spoken_text(translated_text, protected_spans).lower()
    errors: list[str] = []
    for span in protected_spans:
        item = span.to_dict() if isinstance(span, ProtectedSpan) else dict(span)
        canonical = str(item.get("canonical", "")).strip()
        expected_spoken = str(item.get("spoken", "")).strip().lower()
        forbidden = [str(value).lower() for value in item.get("forbidden", []) if str(value).strip()]
        for value in forbidden:
            if value in lower:
                errors.append(f"protected span {canonical} was translated as forbidden term {value}")
        if expected_spoken and expected_spoken not in spoken:
            errors.append(f"protected span {canonical} must be represented as {expected_spoken}")
    return errors

def _load_calculus_profile() -> DomainProfile:
    data = _load_yaml(Path(__file__).with_name("calculus.yaml"))
    return DomainProfile(
        profile_id=str(data.get("id", "calculus")),
        version=str(data.get("version", "1")),
        prompt_summary=str(data.get("prompt_summary", "")).strip(),
        glossary_seeds=list(data.get("glossary_seeds", [])),
        forbidden_translations={
            str(key): [str(item) for item in value]
            for key, value in dict(data.get("forbidden_translations", {})).items()
            if isinstance(value, list)
        },
    )


def _load_yaml(path: Path) -> dict[str, Any]:
    try:
        import yaml  # type: ignore[import-not-found]
    except ModuleNotFoundError:
        if path.name == "calculus.yaml":
            return _calculus_profile_fallback()
        raise

    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return loaded if isinstance(loaded, dict) else {}


def _calculus_profile_fallback() -> dict[str, Any]:
    glossary_seeds = [
        {"original": "dr", "vietnamese": "d r", "category": "calculus_notation", "spoken": "d r", "display": "dr", "forbidden": ["doctor", "bác sĩ", "tiến sĩ"]},
        {"original": "dx", "vietnamese": "d x", "category": "calculus_notation", "spoken": "d x", "display": "dx"},
        {"original": "dy", "vietnamese": "d y", "category": "calculus_notation", "spoken": "d y", "display": "dy"},
        {"original": "dt", "vietnamese": "d t", "category": "calculus_notation", "spoken": "d t", "display": "dt"},
        {"original": "dx squared", "vietnamese": "d x bình phương", "category": "calculus_notation", "spoken": "d x bình phương", "display": "dx²"},
        {"original": "dy/dx", "vietnamese": "d y trên d x", "category": "calculus_notation", "spoken": "d y trên d x", "display": "dy/dx"},
        {"original": "d/dx", "vietnamese": "d trên d x", "category": "calculus_notation", "spoken": "d trên d x", "display": "d/dx"},
        {"original": "πr²", "vietnamese": "pi r bình phương", "category": "formula", "spoken": "pi r bình phương", "display": "πr²"},
        {"original": "½", "vietnamese": "một phần hai", "category": "fraction", "spoken": "một phần hai", "display": "½"},
    ]
    return {
        "id": "calculus",
        "version": "1",
        "prompt_summary": "Calculus notation is technical content. Preserve differential notation and formulas. Never expand dr/dx/dy/dt as English abbreviations or job titles.",
        "glossary_seeds": glossary_seeds,
        "forbidden_translations": {"dr": ["doctor", "bác sĩ", "tiến sĩ"]},
    }


def _detect_calculus_spans(text: str) -> list[ProtectedSpan]:
    spans: list[ProtectedSpan] = []
    specs = [
        (r"dy\s*/\s*dx", "dy/dx", "d y trên d x", "dy/dx", "calculus_notation", "calculus.dy_dx"),
        (r"d\s*/\s*dx", "d/dx", "d trên d x", "d/dx", "calculus_notation", "calculus.d_dx"),
        (r"d\s*/\s*dt", "d/dt", "d trên d t", "d/dt", "calculus_notation", "calculus.d_dt"),
        (r"\bdx\s+squared\b", "dx²", "d x bình phương", "dx²", "calculus_notation", "calculus.dx_squared_words"),
        (r"π\s*r\s*(?:²|\^2)", "πr²", "pi r bình phương", "πr²", "formula", "calculus.pi_r_squared"),
        (r"\bpi\s+r\s+squared\b", "πr²", "pi r bình phương", "πr²", "formula", "calculus.pi_r_squared_words"),
        (r"½|\b1\s*/\s*2\b|\bone\s+half\b", "½", "một phần hai", "½", "fraction", "calculus.one_half"),
    ]
    for pattern, canonical, spoken, display, kind, rule_id in specs:
        for match in re.finditer(pattern, text, flags=re.IGNORECASE):
            spans.append(_span(match, kind, canonical, spoken, display, rule_id))
    for token in ("dr", "dx", "dy", "dt"):
        for match in re.finditer(_WORD_BOUNDARY.format(token=re.escape(token)), text, flags=re.IGNORECASE):
            forbidden = ("doctor", "bác sĩ", "tiến sĩ") if token == "dr" else ()
            spans.append(_span(match, "calculus_notation", token, f"d {token[1]}", token, f"calculus.{token}", forbidden))
    for match in re.finditer(r"(?<![A-Za-zÀ-ỹ])([A-Za-z])\s+of\s+([A-Za-z])\s+squared\b", text, flags=re.IGNORECASE):
        function_name = match.group(1)
        variable = match.group(2)
        canonical = f"{function_name}({variable})²"
        spans.append(_span(match, "power", canonical, f"{function_name}({variable}) bình phương", canonical, "calculus.function_squared_words"))
    for match in re.finditer(r"(?<![A-Za-zÀ-ỹ])([A-Za-z])(?:²|\^2)(?![A-Za-zÀ-ỹ])", text):
        variable = match.group(1)
        spans.append(_span(match, "power", f"{variable}²", f"{variable} bình phương", f"{variable}²", "calculus.variable_squared"))
    for match in re.finditer(r"(?<![A-Za-zÀ-ỹ])([A-Za-z])\s+squared\b", text, flags=re.IGNORECASE):
        variable = match.group(1)
        spans.append(_span(match, "power", f"{variable}²", f"{variable} bình phương", f"{variable}²", "calculus.variable_squared_words"))
    return spans


def _span(
    match: re.Match[str],
    kind: str,
    canonical: str,
    spoken: str,
    display: str,
    rule_id: str,
    forbidden: tuple[str, ...] = (),
) -> ProtectedSpan:
    return ProtectedSpan(
        kind=kind,
        source_text=match.group(0),
        canonical=canonical,
        spoken=spoken,
        display=display,
        start_char=match.start(),
        end_char=match.end(),
        confidence=1.0,
        rule_id=rule_id,
        forbidden=forbidden,
    )


def _dedupe_spans(spans: list[ProtectedSpan]) -> list[ProtectedSpan]:
    ordered = sorted(spans, key=lambda span: (span.start_char, -(span.end_char - span.start_char)))
    result: list[ProtectedSpan] = []
    occupied: list[tuple[int, int]] = []
    for span in ordered:
        if any(not (span.end_char <= start or span.start_char >= end) for start, end in occupied):
            continue
        result.append(span)
        occupied.append((span.start_char, span.end_char))
    return sorted(result, key=lambda span: (span.start_char, span.end_char))


def _safe_id(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_") or "span"
